---
- name: Install common ops packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - "{{ packages }}"

- name: Install common pip packages
  pip:
    name: "{{ item }}"
  with_items:
    - "{{ python_packages }}"

- name: Download kubeval
  get_url:
    src: https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
    dest: /tmp/kubeval-linux-amd64.tar.gz

- name: Install kubeval
  unarchive:
    src: /tmp/kubeval-linux-amd64.tar.gz
    dest: /usr/local/bin
